version: '3'
services:
  php:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    # Add any additional configuration needed

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_assignment
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
